export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_FAILED = 'LOAD_USER_FAILED';
export const LOAD_USER_COMPLETE = 'LOAD_USER_COMPLETE';
export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_USERS_COMPLETE = 'LOAD_USERS_COMPLETE';
export const LOAD_USERS_FAILED = 'LOAD_USERS_FAILED';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_COMPLETE = 'SIGN_IN_COMPLETE';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_COMPLETE = 'SIGN_OUT_COMPLETE';
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED';

export const LOAD_ACCESS_TYPES = 'LOAD_ACCESS_TYPES';
export const LOAD_ACCESS_TYPES_FAILED = 'LOAD_ACCESS_TYPES_FAILED';
export const LOAD_ACCESS_TYPES_COMPLETE = 'LOAD_ACCESS_TYPES_COMPLETE';
